persist_directory: "/root/autodl-tmp/database_1217_opus"

embeddings_model_name: "BAAI/bge-m3"

llm: "Qwen/Qwen2___5-72B-Instruct-AWQ"

# rerank_model : 'BAAI/bge-reranker-v2-gemma'
rerank_model: '/root/autodl-tmp/RAG_Agent_vllm_hhl/src/train_reranker/models/checkpoint-33'

ollama_base_url: "http://127.0.0.1:8000/v1"

# DEBUG, INFO, WARNING, ERROR, CRITICAL
log_level: 'INFO'